# incident-service product routines.
#
# Usage:  make -C products/incident-service <target>   (or cd here and run make)
# Targets come from the shared fragments under ../../mk/. Run `make help`.

IMAGE_NAME := incident-service

include ../../mk/image.mk
include ../../mk/python.mk
