# identity-broker product routines.
#
# Usage:  make -C products/identity-broker <target>   (or cd here and run make)
# Targets come from the shared fragments under ../../mk/. Run `make help`.

IMAGE_NAME := identity-service

include ../../mk/image.mk
include ../../mk/python.mk
