# platform-gateway product routines.
#
# Usage:  make -C products/platform-gateway <target>   (or cd here and run make)
# Targets come from the shared fragments under ../../mk/. Run `make help`.

IMAGE_NAME := platform-gateway

include ../../mk/image.mk
include ../../mk/python.mk
