apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-luban-aiops
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: platform-runtime-config
    envs:
      - shared/runtime.env
      - agent-platform/runtime-config.env
      - platform-gateway/runtime-config.env
      - tool-gateway/runtime-config.env
      - identity-broker/runtime-config.env
  - name: platform-policy
    files:
      - shared/policy.yaml
resources:
  - shared/namespace.yaml
  - infra/redis-deployment.yaml
  - infra/redis-service.yaml
  - operator-portal/web-ui-deployment.yaml
  - operator-portal/web-ui-service.yaml
  - platform-gateway/rbac.yaml
  - platform-gateway/platform-gateway-deployment.yaml
  - platform-gateway/platform-gateway-service.yaml
  - tool-gateway/rbac.yaml
  - tool-gateway/tool-gateway-deployment.yaml
  - tool-gateway/tool-gateway-service.yaml
  - agent-platform/agent-service-deployment.yaml
  - agent-platform/agent-service-service.yaml
  - identity-broker/identity-service-deployment.yaml
  - identity-broker/identity-service-service.yaml
