apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service
spec:
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: agent-service
          command:
            - uv
          args:
            - run
            - agent-service-native
          ports:
            - containerPort: 8080
